"""
Snakefile — IS 477 Final Project: fuelthedata

Workflow automation for data verification, integration, and analysis.

Usage:
    snakemake --cores 1           # Run entire workflow
    snakemake verify_data         # Verify data integrity only
    snakemake clean_and_merge     # Create merged dataset only
"""

DATA_DIR     = "data"
SCRIPTS_DIR  = "scripts"
RESULTS_DIR  = "results"
NOTEBOOK_DIR = "data_analysis"

# Input data files
POVERTY_FILE  = f"{DATA_DIR}/PovertyReport.xlsx"
UNEMPLOY_FILE = f"{DATA_DIR}/UnemploymentReport.xlsx"
CRIME_FILE    = f"{DATA_DIR}/offenses-known-to-le-2024/CIUS_Table_8_Offenses_Known_to_Law_Enforcement_by_State_by_City_2024.xlsx"

# Output files
MERGED_DATA   = f"{RESULTS_DIR}/merged_data.csv"
CHECKSUMS     = "checksums.txt"
NOTEBOOK      = f"{NOTEBOOK_DIR}/dataanalysis_1.ipynb"


rule all:
    """
    Default target: produce merged dataset and verify data integrity.
    
    Note: The full analysis with visualizations is performed in the Jupyter notebook
    (data_analysis/dataanalysis_1.ipynb). To reproduce all figures, run:
        jupyter notebook data_analysis/dataanalysis_1.ipynb
    and execute all cells (Kernel → Restart & Run All).
    """
    input:
        MERGED_DATA,
        CHECKSUMS


rule verify_data:
    """
    Verify SHA-256 checksums of input data files.
    
    Ensures that data files have not been corrupted or altered.
    Reads expected checksums from checksums.txt and compares against
    actual file hashes.
    """
    input:
        POVERTY_FILE,
        UNEMPLOY_FILE,
        CRIME_FILE,
        CHECKSUMS
    output:
        touch(".verify_data.done")  # Create marker file to track completion
    shell:
        """
        echo "Verifying data integrity..."
        python {SCRIPTS_DIR}/download_data.py
        echo "Data verification complete."
        """


rule clean_and_merge:
    """
    Load, clean, and merge the three datasets into a unified state-level dataset.
    
    Steps:
      1. Load poverty, unemployment, and crime data
      2. Clean column names and standardize formatting
      3. Aggregate city-level crime data to state level
      4. Merge datasets on State column
      5. Save to results/merged_data.csv
    
    For detailed documentation of cleaning operations, see scripts/clean_and_merge.py
    """
    input:
        POVERTY_FILE,
        UNEMPLOY_FILE,
        CRIME_FILE,
        ".verify_data.done"  # Ensure data is verified before merging
    output:
        MERGED_DATA
    shell:
        """
        echo "Running data integration..."
        python {SCRIPTS_DIR}/clean_and_merge.py
        echo "Merged dataset created: {output}"
        """


rule run_analysis:
    """
    Execute the analysis notebook to generate visualizations and statistical outputs.
    
    This rule uses jupyter nbconvert to execute the notebook in place.
    The notebook produces:
      - Correlation matrices
      - Scatter plots (poverty/unemployment/income vs. crime)
      - Regression plots
      - Distribution visualizations
    
    All outputs are saved in results/figures/
    """
    input:
        MERGED_DATA,
        NOTEBOOK
    output:
        directory(f"{RESULTS_DIR}/figures")
    shell:
        """
        echo "Executing analysis notebook..."
        jupyter nbconvert --to notebook --execute --inplace {NOTEBOOK}
        echo "Analysis complete. Visualizations saved to {output}/"
        """


rule clean:
    """
    Remove generated files to reset workflow.
    
    Usage:
        snakemake clean
    
    WARNING: This will delete:
      - results/merged_data.csv
      - results/figures/ (if generated by Snakemake)
      - .verify_data.done marker
    """
    shell:
        """
        rm -f {MERGED_DATA}
        rm -f .verify_data.done
        rm -rf {RESULTS_DIR}/figures
        echo "Cleanup complete."
        """
